INSERT INTO Produto(Nome, Preco, Estoque) VALUES('Mouse', 19.20, 10);

SELECT * FROM Produto;

SELECT @@IDENTITY;

CREATE TABLE Pedido (
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_Pedido] PRIMARY KEY,
	NomeCliente VARCHAR(256) NOT NULL,
);

CREATE TABLE ItemPedido (
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_ItemPedido] PRIMARY KEY,
	PedidoId INT NOT NULL CONSTRAINT [FK_ItemPedio_Pedido] FOREIGN KEY REFERENCES Pedido(Id),
	ProdutoId INT NOT NULL CONSTRAINT [FK_ItemPedio_Produto] FOREIGN KEY REFERENCES Produto(Id),
	Quantidade INT NOT NULL
);
SELECT * FROM PEDIDO;

INSERT INTO Pedido(NomeCliente) VALUES('João');

SELECT * FROM PRODUTO;

SELECT * FROM ITEMPEDIDO;

INSERT INTO ItemPedido(PedidoId,ProdutoId,Quantidade) VALUES(17,2,3);

SELECT * FROM ITEMPEDIDO WHERE PEDIDOID = 12;

SELECT * FROM ITEMPEDIDO WHERE PEDIDOID = 17 AND PRODUTOID = 2;