grant DEBUG ANY PROCEDURE to CRESCER2017; --Executar como SYSTEM -LOCAL (PRIVILÉGIOS)

SELECT C.NOME, C.UF FROM CIDADE C ORDER BY C.NOME, C.UF;

SELECT C.NOME, C.IDCIDADE FROM CLIENTE 
  WHERE PCK_CIDADES_DUPLICADAS.PegarNomeCidadeCliente(C.IDCliente) = 'Abadiania' 
        AND PCK_CIDADES_DUPLICADAS.PegarNomeUFCliente(C.IDCliente) = 'GO'; 