// <auto-generated />
namespace CWI.EditoraCresccer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MudancaNoReturnDosLivros : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MudancaNoReturnDosLivros));
        
        string IMigrationMetadata.Id
        {
            get { return "201706012043321_MudancaNoReturnDosLivros"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
