commit;

CREATE TABLE CLIENTE 
(
  ID_CLIENTE NUMBER(8) NOT NULL 
, NM_CLIENTE VARCHAR2(60) NOT NULL 
, CONSTRAINT CLIENTE_PK PRIMARY KEY 
  (
    ID_CLIENTE 
  )
  ENABLE 
);

Select * From Cliente;
INSERT INTO CLIENTE (ID_CLIENTE,NM_CLIENTE) VALUES (1,'Joao');

CREATE TABLE FILHO  (    
   ID_FILHO NUMBER(8), 
    NM_FILHO VARCHAR2(60), 
    ID_PESSOA NUMBER(8)
   ) ;

 ALTER TABLE FILHO ADD CONSTRAINT "FILHO_PK" PRIMARY KEY ("ID_FILHO");

ALTER TABLE FILHO
ADD CONSTRAINT FILHO_FK1 FOREIGN KEY
(
  ID_PESSOA 
)
REFERENCES PESSOA
(
  ID 
)
ENABLE;