DROP TABLE LOCACAO;
DROP TABLE VIDEO;
DROP TABLE GENERO;
DROP TABLE CLIENTE;
DROP TABLE FUNCIONARIO;

DROP SEQUENCE SEQ_FUNCIONARIO;
DROP SEQUENCE SEQ_CLIENTE;
DROP SEQUENCE SEQ_GENERO;
DROP SEQUENCE SEQ_VIDEO;
DROP SEQUENCE SEQ_LOCACAO;

CREATE TABLE FUNCIONARIO ( 
    ID NUMBER(12) NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    BAIRRO VARCHAR2(60),
    CIDADE VARCHAR2(60),
    NUMERO_CASA VARCHAR2(10),
    RUA VARCHAR2(80),
    RG VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(100),
    TELEFONE VARCHAR2(50),
    CELULAR VARCHAR2(50),
    SALARIO DECIMAL(10,2),
    FUNCAO VARCHAR2(50),
    CPF VARCHAR2(11),
    NASCIMENTO DATE, 
    CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (ID)
    ENABLE 
);

CREATE TABLE CLIENTE ( 
    ID NUMBER(12) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    CPF VARCHAR2(11) NOT NULL,
    RG VARCHAR2(15), 
    RUA VARCHAR2(50), 
    BAIRRO VARCHAR2(50), 
    CIDADE VARCHAR2(50), 
    NUMERO_CASA VARCHAR2(50), 
    EMAIL VARCHAR2(50), 
    TELEFONE VARCHAR2(50), 
    CELULAR VARCHAR2(50) NOT NULL,
    NASCIMENTO DATE,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID)
    ENABLE 
);

CREATE TABLE GENERO ( 
    ID NUMBER(12) NOT NULL,
    DESCRICAO VARCHAR2(60) NOT NULL, 
    CONSTRAINT GENERO_PK PRIMARY KEY (ID)
    ENABLE 
); 

CREATE TABLE VIDEO ( 
    ID NUMBER(12) NOT NULL,
    VALOR DECIMAL(6,2) NOT NULL, 
    DURACAO VARCHAR2(50), 
    ID_GENERO NUMBER(12), 
    NOME VARCHAR2(50), 
    QUANTIDADE_ESTOQUE INT,
    DATA_LANCAMENTO DATE,
    FOREIGN KEY(ID_GENERO) REFERENCES GENERO (ID),
    CONSTRAINT VIDEO_PK PRIMARY KEY (ID)
    ENABLE 
);    

CREATE TABLE LOCACAO ( 
    ID NUMBER(12) NOT NULL,
    VALOR_TOTAL DECIMAL(6,2), 
    ID_FUNCIONARIO NUMBER(12), 
    ID_CLIENTE NUMBER(12), 
    ID_VIDEO NUMBER(12), 
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID), 
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID), 
    FOREIGN KEY(ID_VIDEO) REFERENCES VIDEO (ID),
    DATA_DEVOLUCAO DATE,
    CONSTRAINT LOCACAO_PK PRIMARY KEY (ID)
    ENABLE 
);

CREATE SEQUENCE SEQ_FUNCIONARIO  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;

CREATE SEQUENCE SEQ_CLIENTE  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;

CREATE SEQUENCE SEQ_GENERO  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;

CREATE SEQUENCE SEQ_VIDEO  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;

CREATE SEQUENCE SEQ_LOCACAO  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;